use std::fmt::Write;

use serde_json::Value;

use crate::assertions::{AssertValue, JsonAt};

const GENERATE_COMMAND: &str =
    "cargo run -p openengine-cluster-testkit --bin generate-cluster-protocol -- --write";
const MACHINE_DEFINITION_BASE: &str = "../";

const DOWNLOADS: &[(&str, &str)] = &[
    ("openrpc.json", "OpenRPC document"),
    ("schema.json", "Protocol schema"),
    ("graph.schema.json", "Graph schema"),
    ("compiled-ir.schema.json", "Compiled graph IR schema"),
    ("worker.schema.json", "Worker schema"),
    ("run-observation.schema.json", "Run observation schema"),
];

pub(super) fn render(document: &Value) -> String {
    let title = string_at(document.assert_key("info"), "title");
    let protocol_version = string_at(document.assert_key("info"), "version");
    let openrpc_version = string_at(document, "openrpc");
    let mut output = format!(
        "<!-- @generated by `{GENERATE_COMMAND}`; do not edit. -->\n\
         # {title} API reference\n\n\
         Protocol version `{protocol_version}`, described by OpenRPC `{openrpc_version}`.\n\n\
         This page is generated from the checked-in OpenRPC document. Method names, parameters, \
         results, and transport capabilities below are projections of that document.\n\n\
         ## Machine-readable definitions\n\n"
    );
    render_downloads(&mut output);
    render_subscription_framing(document, &mut output);
    output.push_str("## Methods\n\n");
    for method in document
        .assert_key("methods")
        .as_array()
        .assert_value_with("OpenRPC methods must be an array")
    {
        render_method(method, &mut output);
    }
    output.truncate(output.trim_end_matches('\n').len());
    output.push('\n');
    output
}

fn render_downloads(output: &mut String) {
    output.push_str("<ul class=\"api-downloads\">\n");
    for (filename, label) in DOWNLOADS {
        writeln!(
            output,
            "  <li><a href=\"{MACHINE_DEFINITION_BASE}{}\" download>{}</a></li>",
            escape_html(filename),
            escape_html(label)
        )
        .assert_value_with("writing generated API download link must succeed");
    }
    output.push_str("</ul>\n\n");
}

fn render_subscription_framing(document: &Value, output: &mut String) {
    let framing = document.assert_key("x-generic-subscription-framing");
    output.push_str("## Generic subscription framing\n\n");
    writeln!(output, "{}\n", string_at(framing, "description"))
        .assert_value_with("writing generated subscription description must succeed");
    output.push_str("| Notification | Schema |\n| --- | --- |\n");
    for (name, schema) in framing
        .assert_key("notifications")
        .as_object()
        .assert_value_with("OpenRPC generic notifications must be an object")
    {
        writeln!(output, "| {} | {} |", code(name), schema_cell(schema))
            .assert_value_with("writing generated notification row must succeed");
    }
    output.push('\n');
}

fn render_method(method: &Value, output: &mut String) {
    let name = string_at(method, "name");
    let parameter_structure = string_at(method, "paramStructure");
    let subscription = bool_at(method, "x-subscription");
    let transport = method.assert_key("x-transport-requirements");
    let server_push = bool_at(transport, "serverPush");
    let inbound_notifications = bool_at(transport, "inboundNotifications");

    writeln!(output, "### {}\n", code(name))
        .assert_value_with("writing generated method heading must succeed");
    output.push_str(
        "| Parameter structure | Transport | Server push | Inbound notifications |\n\
         | --- | --- | --- | --- |\n",
    );
    writeln!(
        output,
        "| {} | {} | {} | {} |\n",
        code(parameter_structure),
        if subscription {
            "Subscription"
        } else {
            "Unary"
        },
        yes_no(server_push),
        yes_no(inbound_notifications)
    )
    .assert_value_with("writing generated method transport must succeed");

    output.push_str("#### Parameters\n\n");
    let parameters = method
        .assert_key("params")
        .as_array()
        .assert_value_with("OpenRPC method parameters must be an array");
    if parameters.is_empty() {
        output.push_str("This method has no parameters.\n\n");
    } else {
        output.push_str("| Name | Required | Schema |\n| --- | --- | --- |\n");
        for parameter in parameters {
            writeln!(
                output,
                "| {} | {} | {} |",
                code(string_at(parameter, "name")),
                yes_no(bool_at(parameter, "required")),
                schema_cell(parameter.assert_key("schema"))
            )
            .assert_value_with("writing generated method parameter must succeed");
        }
        output.push('\n');
    }

    let result = method.assert_key("result");
    output.push_str("#### Result\n\n| Name | Schema |\n| --- | --- |\n");
    writeln!(
        output,
        "| {} | {} |\n",
        code(string_at(result, "name")),
        schema_cell(result.assert_key("schema"))
    )
    .assert_value_with("writing generated method result must succeed");
}

fn schema_cell(schema: &Value) -> String {
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        return format!(
            "<a href=\"{}\"><code>{}</code></a>",
            schema_href(reference),
            escape_html(reference)
        );
    }
    let schema = serde_json::to_string(schema)
        .assert_value_with("inline OpenRPC parameter schema must serialize");
    code(&schema)
}

fn schema_href(reference: &str) -> String {
    if reference.starts_with('#') {
        escape_html(reference)
    } else {
        format!("{MACHINE_DEFINITION_BASE}{}", escape_html(reference))
    }
}

fn string_at<'a>(value: &'a Value, key: &str) -> &'a str {
    value
        .assert_key(key)
        .as_str()
        .assert_value_with(&format!("OpenRPC {key} must be a string"))
}

fn bool_at(value: &Value, key: &str) -> bool {
    value
        .assert_key(key)
        .as_bool()
        .assert_value_with(&format!("OpenRPC {key} must be a boolean"))
}

const fn yes_no(value: bool) -> &'static str {
    if value { "Yes" } else { "No" }
}

fn code(value: &str) -> String {
    format!("<code>{}</code>", escape_html(value))
}

fn escape_html(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;

    #[test]
    fn renderer_projects_an_unknown_method_from_openrpc() {
        let document = json!({
            "openrpc": "1.3.2",
            "info": { "title": "Fixture Protocol", "version": "7" },
            "methods": [{
                "name": "fixture/custom",
                "paramStructure": "by-name",
                "params": [{
                    "name": "payload",
                    "required": true,
                    "schema": { "$ref": "schema.json#/$defs/FixturePayload" }
                }],
                "result": {
                    "name": "fixtureResult",
                    "schema": { "type": ["string", "null"] }
                },
                "x-subscription": true,
                "x-transport-requirements": {
                    "serverPush": true,
                    "inboundNotifications": false
                }
            }],
            "x-generic-subscription-framing": {
                "description": "Fixture framing.",
                "notifications": {
                    "fixture/event": { "$ref": "schema.json#/$defs/FixtureEvent" }
                }
            }
        });

        let rendered = render(&document);

        assert!(rendered.contains("# Fixture Protocol API reference"));
        assert!(rendered.contains("### <code>fixture/custom</code>"));
        assert!(rendered.contains("| <code>by-name</code> | Subscription | Yes | No |"));
        assert!(rendered.contains(
            "| <code>payload</code> | Yes | <a href=\"../schema.json#/$defs/FixturePayload\""
        ));
        assert!(rendered.contains(
            "| <code>fixtureResult</code> | <code>{&quot;type&quot;:[&quot;string&quot;,&quot;null&quot;]}</code> |"
        ));
        assert!(rendered.contains(
            "| <code>fixture/event</code> | <a href=\"../schema.json#/$defs/FixtureEvent\""
        ));
        assert!(rendered.contains("<a href=\"../openrpc.json\" download>"));
        assert!(rendered.ends_with("</code> |\n"));
    }
}
