use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use clap::{Command, CommandFactory};
use zeroshot_engine::native_v2_cli::Cli;

const MARKDOWN_PATH: &str = "docs/zeroshot-cli.md";
const HTML_PATH: &str = "docs/zeroshot-cli.html";

const GENERATE_COMMAND: &str = "cargo run -p zeroshot --example generate_cli_docs -- --write";

pub(super) struct Documents {
    markdown: String,
    html: String,
}

struct CommandHelp {
    path: String,
    depth: usize,
    text: String,
}

pub(super) fn generate() -> Documents {
    let mut root = Cli::command();
    root.build();

    let mut commands = Vec::new();
    collect_help(&root, 0, &mut commands);

    Documents {
        markdown: render_markdown(&commands),
        html: render_html(&commands),
    }
}

fn repository_root() -> PathBuf {
    let mut root = Path::new(env!("CARGO_MANIFEST_DIR")).to_owned();
    root.pop();
    root
}

pub(super) fn write(documents: &Documents) -> io::Result<Vec<PathBuf>> {
    let root = repository_root();
    let mut changed = Vec::new();
    for (relative, contents) in document_files(documents) {
        let path = root.join(relative);
        if fs::read_to_string(&path).ok().as_deref() != Some(contents) {
            fs::write(&path, contents)?;
            changed.push(path);
        }
    }
    Ok(changed)
}

pub(super) fn stale(documents: &Documents) -> io::Result<Vec<PathBuf>> {
    let root = repository_root();
    let mut stale = Vec::new();
    for (relative, contents) in document_files(documents) {
        let path = root.join(relative);
        match fs::read_to_string(&path) {
            Ok(current) if current == contents => {}
            Ok(_) => stale.push(path),
            Err(error) if error.kind() == io::ErrorKind::NotFound => stale.push(path),
            Err(error) => return Err(error),
        }
    }
    Ok(stale)
}

fn document_files(documents: &Documents) -> [(&'static str, &str); 2] {
    [
        (MARKDOWN_PATH, &documents.markdown),
        (HTML_PATH, &documents.html),
    ]
}

fn collect_help(command: &Command, depth: usize, output: &mut Vec<CommandHelp>) {
    if command.is_hide_set() {
        return;
    }

    let path = command
        .get_bin_name()
        .unwrap_or_else(|| command.get_name())
        .to_owned();
    let mut rendered = command.clone();
    let text = normalize_help(&rendered.render_long_help().to_string());
    output.push(CommandHelp { path, depth, text });

    // Clap's generated help command contains a duplicate copy of the command tree.
    if command.get_name() == "help" {
        return;
    }
    for subcommand in command.get_subcommands() {
        collect_help(subcommand, depth + 1, output);
    }
}

fn render_markdown(commands: &[CommandHelp]) -> String {
    let mut output = format!(
        "<!-- @generated by `{GENERATE_COMMAND}`; do not edit. -->\n\
         # zeroshot CLI reference\n\n\
         This reference is generated from the typed Clap command model and its Rust doc comments.\n\
         Regenerate it with `{GENERATE_COMMAND}`.\n\n"
    );
    for command in commands {
        let heading = "#".repeat((command.depth + 2).min(6));
        output.push_str(&format!(
            "{heading} `{}`\n\n```text\n{}\n```\n\n",
            command.path, command.text
        ));
    }
    if output.ends_with("\n\n") {
        output.pop();
    }
    output
}

fn normalize_help(help: &str) -> String {
    help.lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n")
}

fn render_html(commands: &[CommandHelp]) -> String {
    let mut output = format!(
        "<!doctype html>\n\
         <!-- @generated by `{GENERATE_COMMAND}`; do not edit. -->\n\
         <html lang=\"en\">\n\
         <head>\n\
         <meta charset=\"utf-8\">\n\
         <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n\
         <title>zeroshot CLI reference</title>\n\
         <style>\n\
         :root {{ color-scheme: light dark; font-family: system-ui, sans-serif; }}\n\
         body {{ margin: 0 auto; max-width: 72rem; padding: 2rem; line-height: 1.5; }}\n\
         nav ul {{ columns: 2; padding-left: 1.25rem; }}\n\
         code, pre {{ font-family: ui-monospace, SFMono-Regular, Consolas, monospace; }}\n\
         pre {{ overflow-x: auto; padding: 1rem; border: 1px solid #8886; border-radius: .4rem; background: #8881; }}\n\
         section {{ margin-block: 2.5rem; }}\n\
         .generated {{ color: #666; }}\n\
         @media (max-width: 40rem) {{ body {{ padding: 1rem; }} nav ul {{ columns: 1; }} }}\n\
         </style>\n\
         </head>\n\
         <body>\n\
         <main>\n\
         <h1>zeroshot CLI reference</h1>\n\
         <p class=\"generated\">Generated from the typed Clap command model and its Rust doc comments. \
         Regenerate with <code>{}</code>.</p>\n\
         <nav aria-label=\"Command index\"><h2>Commands</h2><ul>\n",
        escape_html(GENERATE_COMMAND)
    );
    for command in commands {
        output.push_str(&format!(
            "<li><a href=\"#{}\"><code>{}</code></a></li>\n",
            command_anchor(&command.path),
            escape_html(&command.path)
        ));
    }
    output.push_str("</ul></nav>\n");
    for command in commands {
        let level = (command.depth + 2).min(6);
        output.push_str(&format!(
            "<section id=\"{}\"><h{level}><code>{}</code></h{level}>\n\
             <pre><code>{}</code></pre></section>\n",
            command_anchor(&command.path),
            escape_html(&command.path),
            escape_html(&command.text)
        ));
    }
    output.push_str("</main>\n</body>\n</html>\n");
    output
}

fn command_anchor(path: &str) -> String {
    path.replace(' ', "-")
}

fn escape_html(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len());
    for character in value.chars() {
        match character {
            '&' => escaped.push_str("&amp;"),
            '<' => escaped.push_str("&lt;"),
            '>' => escaped.push_str("&gt;"),
            '"' => escaped.push_str("&quot;"),
            '\'' => escaped.push_str("&#39;"),
            _ => escaped.push(character),
        }
    }
    escaped
}
