//! Typed transport-neutral Cluster Protocol client.

mod multiplex;
mod ndjson_pump;
mod ndjson_subscription;

pub mod agent_attach;
pub mod logs;
pub mod native_v2;
pub mod ndjson_agent_attach;
pub mod ndjson_logs;
pub mod ndjson_watch;
pub mod watch;
pub mod websocket;
pub use agent_attach::*;
pub use logs::*;
pub use ndjson_agent_attach::*;
pub use ndjson_logs::*;
pub use ndjson_watch::*;
pub use native_v2::*;
pub use watch::*;
pub use websocket::*;

use std::collections::HashMap;
use std::sync::atomic::{AtomicBool, AtomicI64, Ordering};
use std::sync::Arc;

use parking_lot::Mutex as ParkingMutex;
use async_trait::async_trait;
use openengine_cluster_protocol::{
    ApplyParams, ApplyResult, DeleteParams, DeleteResult, GetParams, GetResult, InitializeParams,
    InitializeResult, JsonRpcError, JsonRpcErrorResponse, JsonRpcRequest, JsonRpcSuccess,
    PlanParams, PlanResult, RequestId, ResubmitParams, ResubmitResult, RetryParams, RetryResult,
    RunDiscardWorkspaceParams, RunDiscardWorkspaceResult, RunForceParams, RunForceResult,
    RunListParams, RunListResult, RunResumeParams, RunResumeResult, RunStatusParams,
    RunStatusResult, RunSubmitParams, RunSubmitResult, StopParams, StopResult, SubscriptionId,
    UpdateParams, UpdateResult, JSON_RPC_VERSION, PROTOCOL_VERSION, RUN_DISCARD_WORKSPACE_METHOD,
    RUN_FORCE_METHOD, RUN_LIST_METHOD, RUN_RESUME_METHOD, RUN_STATUS_METHOD, RUN_SUBMIT_METHOD,
};
use openengine_cluster_server::{ClusterBackend, Dispatcher};
use serde::de::DeserializeOwned;
use serde::Serialize;
use serde_json::Value;
use thiserror::Error;
use tokio::io::{AsyncRead, AsyncWrite, AsyncWriteExt};
use tokio::sync::{mpsc, oneshot, Mutex};
use tokio_stream::StreamExt;
use tokio_util::codec::{FramedRead, LinesCodec};

#[derive(Debug, Error)]
pub enum TransportError {
    #[error("transport I/O failed: {0}")]
    Io(#[from] std::io::Error),
    #[error("transport protocol failed: {0}")]
    Protocol(String),
}

#[async_trait]
pub trait JsonRpcTransport: Send + Sync {
    async fn request(&self, request: String) -> Result<String, TransportError>;
}

/// Forwarding impl so one transport (e.g. an [`NdjsonTransport`]) can back a
/// [`ClusterClient`] and a subscription client (e.g. [`NdjsonWatchClient`]) at the same time,
/// each holding only a shared reference to it.
#[async_trait]
impl<T> JsonRpcTransport for &T
where
    T: JsonRpcTransport + ?Sized,
{
    async fn request(&self, request: String) -> Result<String, TransportError> {
        (**self).request(request).await
    }
}

/// Transport-neutral generic subscription framing: establishing a `watch`/`logs`/`agent/attach`
/// request, cancelling an established subscription, and best-effort cancelling any in-flight
/// unary request by id. Implemented once per wire transport ([`NdjsonTransport`],
/// [`crate::websocket::WebSocketTransport`]) so [`crate::watch::ReconnectingEventStream`]-shaped
/// subscription clients (`WatchSubscriptionClient` and the `logs`/`agent_attach` counterparts
/// generated by the private `ndjson_subscription` helper) drive either transport
/// through the exact same generic code.
#[async_trait]
pub trait SubscriptionTransport: JsonRpcTransport {
    /// Sends a subscription-establishing request and returns its response line plus, only on
    /// success, the receiver registered for its subscription's notifications.
    async fn open_subscription(
        &self,
        request: String,
        id: RequestId,
    ) -> Result<(String, Option<PumpedSubscription>), TransportError>;

    /// Sends a `subscription/cancel` notification. Fire-and-forget: cancellation has no response
    /// on the wire, so this only reports a write failure.
    async fn cancel_subscription(&self, id: SubscriptionId) -> Result<(), TransportError>;

    /// Sends a `$/cancelRequest` notification best-effort cancelling an in-flight unary request by
    /// id. Fire-and-forget, exactly like [`Self::cancel_subscription`]; the server silently
    /// no-ops an unknown or already-completed id and never claims a rollback after commit.
    async fn cancel_request(&self, id: RequestId) -> Result<(), TransportError>;

    /// Mints the next request id for a subscription-establishing request, from a counter shared by
    /// this transport's connection rather than a client-local one, so independently constructed
    /// subscription clients on one connection cannot replace each other's pending response
    /// waiters.
    fn next_watch_request_id(&self) -> RequestId;
}

pub struct InProcessTransport<B> {
    dispatcher: Dispatcher<B>,
}

impl<B> InProcessTransport<B>
where
    B: ClusterBackend,
{
    #[must_use]
    pub const fn new(dispatcher: Dispatcher<B>) -> Self {
        Self { dispatcher }
    }
}

#[async_trait]
impl<B> JsonRpcTransport for InProcessTransport<B>
where
    B: ClusterBackend,
{
    async fn request(&self, request: String) -> Result<String, TransportError> {
        Ok(self.dispatcher.dispatch(&request).await)
    }
}

/// Bounded NDJSON frame length, matching the server's `serve_ndjson` bound.
const MAX_FRAME_BYTES: usize = 1_048_576;

/// Bounded per-subscription local buffer of raw notification lines awaiting
/// [`NdjsonReconnectingEventStream::next`]. Delivery into this queue is non-blocking so one
/// abandoned subscription cannot stall the connection's sole response pump.
const SUBSCRIPTION_QUEUE_CAPACITY: usize = 1024;

/// One demultiplexed unary response: the raw response line plus, only for a successful `watch`
/// response, the freshly registered receiver for that subscription's `event`/`subscription/closed`
/// notifications.
struct PumpedResponse {
    line: String,
    subscription: Option<PumpedSubscription>,
}

/// Opaque per-subscription handle handed from [`SubscriptionTransport::open_subscription`] to a
/// subscription client: the receiver end of that subscription's forwarded notification lines,
/// plus the shared overflow flag its pump sets on a full/abandoned local queue. Its fields are
/// crate-private; only [`SubscriptionTransport`] implementors and subscription clients wire them.
pub struct PumpedSubscription {
    pub(crate) receiver: mpsc::Receiver<String>,
    pub(crate) overflowed: Arc<AtomicBool>,
}

#[derive(Clone)]
struct SubscriptionRegistration {
    sender: mpsc::Sender<String>,
    overflowed: Arc<AtomicBool>,
}

type PendingMap = Arc<ParkingMutex<HashMap<RequestId, oneshot::Sender<PumpedResponse>>>>;
type SubscriptionMap = Arc<ParkingMutex<HashMap<SubscriptionId, SubscriptionRegistration>>>;

/// Writes one line (a trailing `\n`, flushed) to a shared writer -- the [`multiplex::FrameSink`]
/// implementation backing [`NdjsonTransport`].
struct NdjsonFrameSink<W> {
    writer: Arc<Mutex<W>>,
}

#[async_trait]
impl<W> multiplex::FrameSink for NdjsonFrameSink<W>
where
    W: AsyncWrite + Send + Unpin,
{
    async fn send_frame(&self, frame: String) -> Result<(), TransportError> {
        let mut writer = self.writer.lock().await;
        writer.write_all(frame.as_bytes()).await?;
        writer.write_all(b"\n").await?;
        writer.flush().await?;
        Ok(())
    }
}

/// NDJSON stdio transport that demultiplexes unary request/response traffic and generic `watch`
/// subscription notifications sharing one connection, correlating by request id and subscription
/// id respectively. Holds one private `MultiplexedTransport`, which owns the demux state
/// (write sink, pending-request map, pump task, watch-id counter) and implements every
/// [`JsonRpcTransport`]/[`SubscriptionTransport`] method against it -- see
/// [`crate::websocket::WebSocketTransport`] for the identical WebSocket-frame binding.
pub struct NdjsonTransport<R, W> {
    inner: multiplex::MultiplexedTransport<NdjsonFrameSink<W>>,
    _reader: std::marker::PhantomData<fn() -> R>,
}

impl<R, W> NdjsonTransport<R, W>
where
    R: AsyncRead + Send + Unpin + 'static,
    W: AsyncWrite + Send + Unpin + 'static,
{
    #[must_use]
    pub fn new(reader: R, writer: W) -> Self {
        let pending: PendingMap = Arc::new(ParkingMutex::new(HashMap::new()));
        let subscriptions: SubscriptionMap = Arc::new(ParkingMutex::new(HashMap::new()));
        let sink = NdjsonFrameSink {
            writer: Arc::new(Mutex::new(writer)),
        };
        let pump = tokio::spawn(run_pump(
            reader,
            Arc::clone(&pending),
            subscriptions,
            NdjsonFrameSink {
                writer: Arc::clone(&sink.writer),
            },
        ));
        Self {
            inner: multiplex::MultiplexedTransport::new(sink, pending, pump),
            _reader: std::marker::PhantomData,
        }
    }
}

multiplex::impl_multiplexed_transport!(
    NdjsonTransport<R, W> where
    R: AsyncRead + Send + Unpin + 'static,
    W: AsyncWrite + Send + Unpin + 'static
);

/// Extracts the `id` from an outgoing request this crate serialized itself.
fn extract_request_id(request: &str) -> Result<RequestId, TransportError> {
    serde_json::from_str::<JsonRpcRequest<Value>>(request)
        .map(|request| request.id)
        .map_err(|error| TransportError::Protocol(error.to_string()))
}

/// Drives the read half: decodes bounded NDJSON lines and routes each one via
/// [`multiplex::route_and_maybe_cancel`] -- shared verbatim with
/// [`crate::websocket::WebSocketTransport`]'s pump, which routes the exact same decoded JSON
/// bodies sourced from `Message::Text` frames instead of NDJSON lines. On stream end every pending
/// request fails and every open subscription ends (dropping its sender).
async fn run_pump<R, W>(
    reader: R,
    pending: PendingMap,
    subscriptions: SubscriptionMap,
    sink: NdjsonFrameSink<W>,
) where
    R: AsyncRead + Unpin,
    W: AsyncWrite + Unpin + Send,
{
    let mut lines = FramedRead::new(reader, LinesCodec::new_with_max_length(MAX_FRAME_BYTES));
    while let Some(Ok(line)) = lines.next().await {
        multiplex::route_and_maybe_cancel(line, &pending, &subscriptions, &sink).await;
    }
    multiplex::finish_pump(&pending, &subscriptions);
}

pub struct ClusterClient<T> {
    transport: T,
    next_id: AtomicI64,
}

impl<T> ClusterClient<T>
where
    T: JsonRpcTransport,
{
    #[must_use]
    pub const fn new(transport: T) -> Self {
        Self {
            transport,
            next_id: AtomicI64::new(1),
        }
    }

    pub async fn initialize(&self) -> Result<InitializeResult, ClientError> {
        self.initialize_with_version(PROTOCOL_VERSION).await
    }

    pub async fn initialize_with_version(
        &self,
        protocol_version: impl Into<String> + Send,
    ) -> Result<InitializeResult, ClientError> {
        let protocol_version = protocol_version.into();
        let result: InitializeResult = self
            .call(
                "initialize",
                InitializeParams {
                    protocol_version: protocol_version.clone(),
                },
            )
            .await?;
        if result.protocol_version != protocol_version {
            return Err(ClientError::InvalidResponse(format!(
                "protocol version mismatch: requested {protocol_version}, received {}",
                result.protocol_version
            )));
        }
        result
            .validate_protocol_version()
            .map_err(|error| ClientError::InvalidResponse(error.to_string()))?;
        Ok(result)
    }

    pub async fn plan(&self, params: PlanParams) -> Result<PlanResult, ClientError> {
        self.call("plan", params).await
    }

    pub async fn apply(&self, params: ApplyParams) -> Result<ApplyResult, ClientError> {
        self.call("apply", params).await
    }

    pub async fn get(&self, params: GetParams) -> Result<GetResult, ClientError> {
        self.call("get", params).await
    }

    pub async fn update(&self, params: UpdateParams) -> Result<UpdateResult, ClientError> {
        self.call("update", params).await
    }

    pub async fn stop(&self, params: StopParams) -> Result<StopResult, ClientError> {
        self.call("stop", params).await
    }

    pub async fn retry(&self, params: RetryParams) -> Result<RetryResult, ClientError> {
        self.call("retry", params).await
    }

    pub async fn resubmit(&self, params: ResubmitParams) -> Result<ResubmitResult, ClientError> {
        self.call("resubmit", params).await
    }

    pub async fn delete(&self, params: DeleteParams) -> Result<DeleteResult, ClientError> {
        self.call("delete", params).await
    }

    pub async fn run_submit(
        &self,
        params: RunSubmitParams,
    ) -> Result<RunSubmitResult, ClientError> {
        self.call(RUN_SUBMIT_METHOD, params).await
    }

    pub async fn run_list(&self, params: RunListParams) -> Result<RunListResult, ClientError> {
        self.call(RUN_LIST_METHOD, params).await
    }

    pub async fn run_status(
        &self,
        params: RunStatusParams,
    ) -> Result<RunStatusResult, ClientError> {
        self.call(RUN_STATUS_METHOD, params).await
    }

    pub async fn run_force(&self, params: RunForceParams) -> Result<RunForceResult, ClientError> {
        self.call(RUN_FORCE_METHOD, params).await
    }

    pub async fn run_resume(
        &self,
        params: RunResumeParams,
    ) -> Result<RunResumeResult, ClientError> {
        self.call(RUN_RESUME_METHOD, params).await
    }

    pub async fn run_discard_workspace(
        &self,
        params: RunDiscardWorkspaceParams,
    ) -> Result<RunDiscardWorkspaceResult, ClientError> {
        self.call(RUN_DISCARD_WORKSPACE_METHOD, params).await
    }

    async fn call<P, R>(&self, method: &str, params: P) -> Result<R, ClientError>
    where
        P: Serialize + Send,
        R: DeserializeOwned,
    {
        let id = RequestId::Integer(self.next_id.fetch_add(1, Ordering::Relaxed));
        let request = serde_json::to_string(&JsonRpcRequest {
            jsonrpc: JSON_RPC_VERSION.to_owned(),
            id: id.clone(),
            method: method.to_owned(),
            params,
        })?;
        let response = self.transport.request(request).await?;
        let value: Value = serde_json::from_str(&response)
            .map_err(|error| ClientError::InvalidResponse(error.to_string()))?;

        if value.get("error").is_some() {
            let response: JsonRpcErrorResponse = serde_json::from_value(value)
                .map_err(|error| ClientError::InvalidResponse(error.to_string()))?;
            validate_response_identity(&response.jsonrpc, response.id.as_ref(), &id)?;
            return Err(ClientError::Rpc(response.error));
        }

        let response: JsonRpcSuccess<R> = serde_json::from_value(value)
            .map_err(|error| ClientError::InvalidResponse(error.to_string()))?;
        validate_response_identity(&response.jsonrpc, Some(&response.id), &id)?;
        Ok(response.result)
    }
}

fn validate_response_identity(
    jsonrpc: &str,
    actual_id: Option<&RequestId>,
    expected_id: &RequestId,
) -> Result<(), ClientError> {
    if jsonrpc != JSON_RPC_VERSION {
        return Err(ClientError::InvalidResponse(format!(
            "expected jsonrpc {JSON_RPC_VERSION}, received {jsonrpc}"
        )));
    }
    if actual_id != Some(expected_id) {
        return Err(ClientError::InvalidResponse(format!(
            "response id mismatch: expected {expected_id:?}, received {actual_id:?}"
        )));
    }
    Ok(())
}

#[derive(Debug, Error)]
pub enum ClientError {
    #[error(transparent)]
    Transport(#[from] TransportError),
    #[error("request serialization failed: {0}")]
    Serialization(#[from] serde_json::Error),
    #[error("server returned JSON-RPC error {0:?}")]
    Rpc(JsonRpcError),
    #[error("invalid JSON-RPC response: {0}")]
    InvalidResponse(String),
    #[error(transparent)]
    Backend(#[from] openengine_cluster_server::BackendError),
}
