//! Client-side NDJSON `agent/attach` subscription coverage: establishment, ordered
//! Working->Output->Settled delivery, cancellation, and unknown/inactive-execution error
//! propagation, driven over the wire against `serve_ndjson`.
//!
//! Generic wire-protocol machinery -- independent request-id sourcing, malformed/unexpected
//! notification handling, and unread-subscription overflow not blocking unary responses -- has no
//! counterpart here: `NdjsonAgentAttachClient`/`NdjsonAgentAttachEventStream` are generated by the
//! exact same [`openengine_cluster_client::ndjson_subscription::impl_ndjson_event_subscription`]
//! macro invocation as `NdjsonLogsClient`/`NdjsonLogsEventStream`, so that machinery is already
//! exhaustively covered once, generically, by `tests/logs.rs`; re-testing it per capability would
//! exercise the exact same generated code a second time.

use std::sync::Arc;

use openengine_cluster_client::{
    AgentAttachClient, AgentAttachEventOrClosed, NdjsonAgentAttachClient,
    NdjsonAgentAttachEventStream, NdjsonTransport,
};
use openengine_cluster_protocol::{
    AgentAttachEvent, AgentAttachParams, BoundedAssistantOutput, ExecutionRef, GONE, NOT_FOUND,
};
use openengine_cluster_server::agent_attach::fixtures::{
    AgentAttachFixtureBackend, AgentAttachFixtureStore,
};
use openengine_cluster_server::agent_attach::AgentAttachStreamItem;
use openengine_cluster_server::watch::fixtures::{await_ndjson_shutdown, spawn_ndjson};
use openengine_cluster_server::{ConnectionContext, Dispatcher};
use tokio::io::DuplexStream;

#[path = "support/mod.rs"]
pub mod support;
use support::AssertValue;

#[path = "cancel_leak_support/mod.rs"]
mod cancel_leak_support;
use cancel_leak_support::assert_cancel_stops_further_delivery;

fn sample_execution_ref() -> ExecutionRef {
    ExecutionRef::new("execution-1").assert_value()
}

fn agent_attach_params() -> AgentAttachParams {
    AgentAttachParams {
        execution: sample_execution_ref(),
    }
}

fn sample_output_event(text: &str) -> AgentAttachEvent {
    AgentAttachEvent::Output {
        text: BoundedAssistantOutput::new(text).assert_value(),
    }
}

/// Awaits the stream's next item and asserts it is the given event, exactly.
async fn expect_next_event(
    stream: &mut NdjsonAgentAttachEventStream<'_, DuplexStream, DuplexStream>,
    expected: &AgentAttachEvent,
) {
    let event = match stream.next().await.assert_value().assert_value() {
        AgentAttachEventOrClosed::Event(event) => Some(event),
        AgentAttachEventOrClosed::Closed { .. } => None,
    }
    .assert_value_with("expected an agent attach event");
    assert_eq!(&event, expected);
}

async fn assert_attach_rejection(
    store: Arc<AgentAttachFixtureStore>,
    expected_code: &str,
    context: &str,
) {
    let (client_write, client_read, server) =
        spawn_ndjson(AgentAttachFixtureBackend::new(Arc::clone(&store)));
    let transport = NdjsonTransport::new(client_read, client_write);
    let error = NdjsonAgentAttachClient::new(&transport)
        .agent_attach(agent_attach_params())
        .await
        .err()
        .assert_value_with(context);
    let rpc_error = match error {
        openengine_cluster_client::ClientError::Rpc(error) => Some(error),
        _ => None,
    }
    .assert_value_with("expected an RPC error");
    assert_eq!(
        rpc_error.data.as_ref().map(|data| data.code.as_str()),
        Some(expected_code)
    );
    drop(transport);
    await_ndjson_shutdown(server).await;
}

#[tokio::test]
async fn establish_stream_working_output_settled_then_cancel_stops_delivery() {
    let store = Arc::new(AgentAttachFixtureStore::new());
    let execution = sample_execution_ref();
    store.register_active(execution.clone()).await;
    let (client_write, client_read, server) =
        spawn_ndjson(AgentAttachFixtureBackend::new(Arc::clone(&store)));

    let transport = NdjsonTransport::new(client_read, client_write);
    let agent_attach_client = NdjsonAgentAttachClient::new(&transport);
    let (_result, mut stream) = agent_attach_client
        .agent_attach(agent_attach_params())
        .await
        .assert_value();

    for event in [
        AgentAttachEvent::Working {},
        sample_output_event("hello"),
        AgentAttachEvent::Settled {},
    ] {
        store.publish(&execution, event.clone()).await;
        expect_next_event(&mut stream, &event).await;
    }

    assert_cancel_stops_further_delivery(
        &mut stream,
        &transport,
        |text| store.publish(&execution, sample_output_event(text)),
        |item| match item {
            AgentAttachEventOrClosed::Event(AgentAttachEvent::Output { text }) => {
                Some(text.as_str().to_owned())
            }
            _ => None,
        },
    )
    .await;

    drop(stream);
    drop(transport);
    await_ndjson_shutdown(server).await;
}

#[tokio::test]
async fn unknown_execution_ref_error_propagates_to_the_client() {
    let store = Arc::new(AgentAttachFixtureStore::new());
    assert_attach_rejection(
        store,
        NOT_FOUND,
        "expected an unknown execution ref rejection",
    )
    .await;
}

#[tokio::test]
async fn inactive_execution_ref_error_propagates_to_the_client() {
    let store = Arc::new(AgentAttachFixtureStore::new());
    let execution = sample_execution_ref();
    store.register_active(execution.clone()).await;
    store.mark_inactive(&execution).await;
    assert_attach_rejection(store, GONE, "expected an inactive execution ref rejection").await;
}

#[tokio::test]
async fn typed_client_delegates_attach_establishment_and_live_events() {
    let store = Arc::new(AgentAttachFixtureStore::new());
    let execution = sample_execution_ref();
    store.register_active(execution.clone()).await;
    let client = AgentAttachClient::new(Dispatcher::new(
        AgentAttachFixtureBackend::new(Arc::clone(&store)),
        ConnectionContext::default(),
    ));

    let (result, mut stream, handle) = client
        .agent_attach(agent_attach_params())
        .await
        .assert_value();
    assert!(!result.subscription_id.as_str().is_empty());

    let expected = sample_output_event("typed client");
    store.publish(&execution, expected.clone()).await;
    assert_eq!(
        stream.next().await,
        Some(AgentAttachStreamItem::Event(expected))
    );
    drop(handle);
}
