const PROTOCOL_VERSION = 1;
const MAX_FRAME_BYTES = 10 * 1024 * 1024;

const RPC_ERROR_CODES = Object.freeze({
  PARSE_ERROR: -32700,
  INVALID_REQUEST: -32600,
  METHOD_NOT_FOUND: -32601,
  INVALID_PARAMS: -32602,
  INTERNAL_ERROR: -32603,
  PROTOCOL_VERSION_MISMATCH: -32000,
  ORCHESTRATOR_UNAVAILABLE: -32001,
  CLUSTER_NOT_FOUND: -32002,
  UNSUPPORTED_CAPABILITY: -32003,
});

const RPC_ERROR_MESSAGES = Object.freeze({
  [RPC_ERROR_CODES.PARSE_ERROR]: 'Parse error',
  [RPC_ERROR_CODES.INVALID_REQUEST]: 'Invalid request',
  [RPC_ERROR_CODES.METHOD_NOT_FOUND]: 'Method not found',
  [RPC_ERROR_CODES.INVALID_PARAMS]: 'Invalid params',
  [RPC_ERROR_CODES.INTERNAL_ERROR]: 'Internal error',
  [RPC_ERROR_CODES.PROTOCOL_VERSION_MISMATCH]: 'Protocol version mismatch',
  [RPC_ERROR_CODES.ORCHESTRATOR_UNAVAILABLE]: 'Orchestrator unavailable',
  [RPC_ERROR_CODES.CLUSTER_NOT_FOUND]: 'Cluster not found',
  [RPC_ERROR_CODES.UNSUPPORTED_CAPABILITY]: 'Unsupported capability',
});

module.exports = {
  PROTOCOL_VERSION,
  MAX_FRAME_BYTES,
  RPC_ERROR_CODES,
  RPC_ERROR_MESSAGES,
};
