const USER_GUIDANCE_CLUSTER = 'USER_GUIDANCE_CLUSTER';
const USER_GUIDANCE_AGENT = 'USER_GUIDANCE_AGENT';

const GUIDANCE_TOPICS = [USER_GUIDANCE_CLUSTER, USER_GUIDANCE_AGENT];

module.exports = {
  USER_GUIDANCE_CLUSTER,
  USER_GUIDANCE_AGENT,
  GUIDANCE_TOPICS,
};
